spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev
    application:
        name: service-config-dev
---
spring:
    profiles: test
    application:
        name: service-config-test